# Title Name: The Amazing Spider-Man
# Title ID: 415608B5

[GPU]
occlusion_query = "strict" # Fixes unoccluded lens flares
occlusion_query_full_counters = true # Fixes unoccluded lens flares
render_target_path_d3d12 = "rov" # Fixes lighting issues