# Title Name: Disney Epic Mickey 2: The Power of Two
# Title ID: 42560816

[GPU]
occlusion_query = "fake" # Fixes flickering and performance issues
occlusion_query_querybatch_range = 8 # Fixes flickering and performance issues