# Title Name: Dead Rising
# Title ID: 434307D2

[APU]
use_dedicated_xma_thread = false # Fixes missing or broken audio
xma_decoder = "new" # Fixes missing or broken audio

[GPU]
clear_memory_page_state = true # Fixes warped graphics in game
render_target_path_d3d12 = "rov" # Fixes broken character models