# Title Name: FUSE
# Title ID: 4541096E

[GPU]
query_occlusion_sample_lower_threshold = 0 # Fixes lens flares
query_occlusion_sample_upper_threshold = 0 # Fixes lens flares
readback_resolve = "full" # Stops the game from hanging during the intro