# Title Name: Fight Night Champion
# Title ID: 45410915

[GPU]
clear_memory_page_state = true # Fixes warped graphics ingame
readback_resolve = "full" # Fixes the textures
vsync = false # Unlocks framerate (Combined with framerate limit set to 0)

[Storage]
mount_scratch = true # Needed for instant replays