# Title Name: Fifa Street
# Title ID: 4541097B

[GPU]
framerate_limit = 0 # Unlocks framerate (Combined with disabled vertical sync)
readback_resolve = "full" # Fixes the textures at the cost of performance
vsync = false # Unlocks framerate (Combined with framerate limit set to 0)