# Title Name: NHL 14
# Title ID: 454109BE

[CPU]
disable_context_promotion = true # Fixes animations and stops the game from crashing

[GPU]
framerate_limit = 120 # Caps the FPS to 60
readback_resolve = "full" # Fixes the player uniforms