# Title Name: Tenchu Z
# Title ID: 465307D7

[GPU]
clear_memory_page_state = true # Fixes warped graphics in game
use_fuzzy_alpha_epsilon = true # Fixes the noise in game

[General]
time_scalar = 4 # Makes the game start

[Memory]
protect_zero = false # Stops the game from crashing