# Title Name: Halo Combat Evolved Anniversary
# Title ID: 4D5309B1

[GPU]
clear_memory_page_state = true # Fixes warped graphics in game
occlusion_query_querybatch_range = 256 # Fixes textures not loading
occlusion_query = "fake" # Fixes textures not loading