# Title Name: Gears of War 3
# Title ID: 4D5308AB

[GPU]
draw_resolution_scale_threshold = 360 # Fixes post-process effects when using resolution scaling. Doesn't activate when rendering 1x1.
vsync = false # Unlocks framerate (Combined with framerate limit set to 0)

[Kernel]
cl = "-NoStartupMovies" # Skips intro

[Memory]
protect_zero = false # Stops the game from freezing