# Title Name: Gears of War 2
# Title ID: 4D53082D

[GPU]
draw_resolution_scale_threshold = 360 # Fixes post-process effects when using resolution scaling. Doesn't activate when rendering 1x1.
vsync = false # Unlocks framerate (Combined with framerate limit set to 0)

[Kernel]
cl = "-NoStartupMovies" # Skips intro