# Title Name: Forza Motorsport 2
# Title ID: 4D5307EA

[GPU]
framerate_limit = 0 # Unlocks framerate (Combined with disabled vertical sync)
query_occlusion_sample_lower_threshold = -1 # stops the lights rendering through the walls
vsync = false # Unlocks framerate (Combined with framerate limit set to 0)

[Storage]
mount_cache = true # Needed for instant replays