# Title Name: Forza Horizon 2
# Title ID: 4D530AA4

[APU]
use_dedicated_xma_thread = false # Fixes audio stuff
xma_decoder = "new" # Fixes audio stuff

[GPU]
framerate_limit = 0 # Unlocks framerate (Combined with disabled vertical sync)
gpu_allow_invalid_fetch_constants = true # Fixes missing mirrors
readback_resolve = "full" # Fixes designs and thumbnails of cars at the cost of performance
vsync = false # Unlocks framerate (Combined with framerate limit set to 0)

[General]
controller_hotkeys = true # Turn off Readback_Resolve with A + Guide Button when the car thumbnails work

[Storage]
mount_cache = true # Stops the game from crashing when starting a race