# Title Name: Tekken Tag Tournament 2
# Title ID: 4E4D0859

[GPU]
framerate_limit = 120 # Fixes slowmo in online
readback_resolve = "full" #Fixes the black clothing on characters but performance will be reduced

[General]
time_scalar = 4 # Makes the game start

[Memory]
protect_zero = false # Stops the game from crashing