# Title Name: Armored Core - Verdict Day
# Title ID: 4E4D0864

[APU]
use_dedicated_xma_thread = false # Stops the game from crashing
xma_decoder = "new" # Stops the game from crashing

[GPU]
framerate_limit = 0 # Unlocks framerate
readback_resolve = "full" # Fixes the textures at the cost of performance
vsync = false # Unlocks framerate

[General]
controller_hotkeys = true # Turn off Readback_Resolve with A + Guide Button after a few seconds

[Memory]
protect_zero = false # Stops the game from crashing