# Title Name: Tomb Raider: Legend
# Title ID: 534307D4

[APU]
use_dedicated_xma_thread = false                             # Used with the setting below.
xma_decoder = "new"                             # Fixes the softlocking.

[GPU]
framerate_limit = 120                             # 60 FPS cap.