# Title Name: Naruto - The Broken Bond
# Title ID: 55530825

[APU]
use_dedicated_xma_thread = false # Fixes missing/broken audio
xma_decoder = "new" # Fixes missing/broken audio

[GPU]
clear_memory_page_state = true # Fixes warped graphics in game
gpu_allow_invalid_upload_range = true # Fixes warped graphics in game