# Title Name: Fable Heroes
# Title ID: 58410B86

[GPU]
framerate_limit = 0 # Unlocks framerate (Combined with disabled vertical sync)
readback_resolve = "full" # Fixes brightness
vsync = false # Unlocks framerate (Combined with framerate limit set to 0)