# Title Name: Hydro Thunder Hurricane
# Title ID: 5841096A

[GPU]
readback_resolve = "fast" # Fixes brightness at the cost of performance
[Storage]
mount_scratch = true                              	# Enable scratch mount
[Content]
license_mask = 1                                  	# Set license mask for activated content.
