[Live]
api_address = "https://xenia-netplay-2a0298c0e3f4.herokuapp.com" 	                  # Xenia Server Address
api_list = "https://xenia-netplay-2a0298c0e3f4.herokuapp.com/,192.168.0.1:36000/" 	# 
