# Title Name: Portal - Still Alive
# Title ID: 58410960

[CPU]
break_on_unimplemented_instructions = false # Stops the game from crashing

[GPU]
clear_memory_page_state = true # Fixes warped graphics in game
readback_resolve = "fast" # Fixes the garbled text
occlusion_query_saturation = 0.7 # Fixes excessive lighting

[Kernel]
cl = "-dvd -game portal +fps_max 0" # Boots the game and unlocks framerate